#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

// Raw Porcupine C FFI - generated by bindgen in build.rs
// This module must not contain any logic. Unsafe C symbols are exposed here only.
include!(concat!(env!("OUT_DIR"), "/porcupine_bindings.rs"));
